/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const AccountStatus: core.schemas.Schema<AccountStatus.Raw, PhylloConnectApi.connect.AccountStatus> =
  core.schemas.string().transform<PhylloConnectApi.connect.AccountStatus>({
    parse: (value) => PhylloConnectApi.connect.AccountStatus._parse(value),
    json: ({ value }) => value,
  });

export declare namespace AccountStatus {
  type Raw = string;
}
