/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const AllWorkPlatformsResponse: core.schemas.ObjectSchema<
  AllWorkPlatformsResponse.Raw,
  PhylloConnectApi.connect.AllWorkPlatformsResponse
> = core.schemas.object({
  data: core.schemas.list(core.schemas.lazyObject(() => serializers.connect.WorkPlatform)),
  metadata: core.schemas.lazyObject(() => serializers.connect.Metadata),
});

export declare namespace AllWorkPlatformsResponse {
  interface Raw {
    data: serializers.connect.WorkPlatform.Raw[];
    metadata: serializers.connect.Metadata.Raw;
  }
}
