/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const DataStatus: core.schemas.Schema<DataStatus.Raw, PhylloConnectApi.connect.DataStatus> = core.schemas
  .string()
  .transform<PhylloConnectApi.connect.DataStatus>({
    parse: (value) => PhylloConnectApi.connect.DataStatus._parse(value),
    json: ({ value }) => value,
  });

export declare namespace DataStatus {
  type Raw = string;
}
