/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const EngagementData: core.schemas.ObjectSchema<EngagementData.Raw, PhylloConnectApi.connect.EngagementData> =
  core.schemas.object({
    status: core.schemas.lazy(() => serializers.connect.DataStatus),
    lastSyncAt: core.schemas.property("last_sync_at", core.schemas.date().optional()),
    refreshSince: core.schemas.property("refresh_since", core.schemas.date().optional()),
    dataAvailableFrom: core.schemas.property("data_available_from", core.schemas.date().optional()),
    monitorType: core.schemas.property(
      "monitor_type",
      core.schemas.lazy(() => serializers.connect.MonitoringType)
    ),
    audience: core.schemas.lazyObject(() => serializers.connect.EngagementAudienceData).optional(),
  });

export declare namespace EngagementData {
  interface Raw {
    status: serializers.connect.DataStatus.Raw;
    last_sync_at?: string | null;
    refresh_since?: string | null;
    data_available_from?: string | null;
    monitor_type: serializers.connect.MonitoringType.Raw;
    audience?: serializers.connect.EngagementAudienceData.Raw | null;
  }
}
