/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const IdentityProduct: core.schemas.ObjectSchema<IdentityProduct.Raw, PhylloConnectApi.connect.IdentityProduct> =
  core.schemas.object({
    isSupported: core.schemas.property("is_supported", core.schemas.boolean()),
    audience: core.schemas.lazyObject(() => serializers.connect.Audience),
  });

export declare namespace IdentityProduct {
  interface Raw {
    is_supported: boolean;
    audience: serializers.connect.Audience.Raw;
  }
}
