/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const Metadata: core.schemas.ObjectSchema<Metadata.Raw, PhylloConnectApi.connect.Metadata> = core.schemas.object(
  {
    offset: core.schemas.number(),
    limit: core.schemas.number(),
    fromDate: core.schemas.property("from_date", core.schemas.string().optional()),
    toDate: core.schemas.property("to_date", core.schemas.string().optional()),
  }
);

export declare namespace Metadata {
  interface Raw {
    offset: number;
    limit: number;
    from_date?: string | null;
    to_date?: string | null;
  }
}
