/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const PhylloProducts: core.schemas.Schema<PhylloProducts.Raw, PhylloConnectApi.connect.PhylloProducts> =
  core.schemas.string().transform<PhylloConnectApi.connect.PhylloProducts>({
    parse: (value) => PhylloConnectApi.connect.PhylloProducts._parse(value),
    json: ({ value }) => value,
  });

export declare namespace PhylloProducts {
  type Raw = string;
}
