/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const Products: core.schemas.ObjectSchema<Products.Raw, PhylloConnectApi.connect.Products> = core.schemas.object(
  {
    identity: core.schemas.lazyObject(() => serializers.connect.IdentityProduct),
    engagement: core.schemas.lazyObject(() => serializers.connect.EngagementProduct),
    income: core.schemas.lazyObject(() => serializers.connect.IncomeProduct),
    switch: core.schemas.lazyObject(() => serializers.connect.SwitchProduct),
  }
);

export declare namespace Products {
  interface Raw {
    identity: serializers.connect.IdentityProduct.Raw;
    engagement: serializers.connect.EngagementProduct.Raw;
    income: serializers.connect.IncomeProduct.Raw;
    switch: serializers.connect.SwitchProduct.Raw;
  }
}
