/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const SDKTokenResponse: core.schemas.ObjectSchema<
  SDKTokenResponse.Raw,
  PhylloConnectApi.connect.SDKTokenResponse
> = core.schemas.object({
  sdkToken: core.schemas.property("sdk_token", core.schemas.string()),
  expiresAt: core.schemas.property("expires_at", core.schemas.date()),
});

export declare namespace SDKTokenResponse {
  interface Raw {
    sdk_token: string;
    expires_at: string;
  }
}
