/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const Status: core.schemas.Schema<Status.Raw, PhylloConnectApi.connect.Status> = core.schemas
  .string()
  .transform<PhylloConnectApi.connect.Status>({
    parse: (value) => PhylloConnectApi.connect.Status._parse(value),
    json: ({ value }) => value,
  });

export declare namespace Status {
  type Raw = string;
}
