/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const UserId: core.schemas.Schema<UserId.Raw, PhylloConnectApi.connect.UserId> = core.schemas.string();

export declare namespace UserId {
  type Raw = string;
}
