/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const UserAttribute: core.schemas.ObjectSchema<UserAttribute.Raw, PhylloConnectApi.connect.UserAttribute> =
  core.schemas.object({
    id: core.schemas.lazy(() => serializers.connect.UserId),
    name: core.schemas.string(),
  });

export declare namespace UserAttribute {
  interface Raw {
    id: serializers.connect.UserId.Raw;
    name: string;
  }
}
