/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const WorkPlatformId: core.schemas.Schema<WorkPlatformId.Raw, PhylloConnectApi.connect.WorkPlatformId> =
  core.schemas.string();

export declare namespace WorkPlatformId {
  type Raw = string;
}
