/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const WorkPlatform: core.schemas.ObjectSchema<WorkPlatform.Raw, PhylloConnectApi.connect.WorkPlatform> =
  core.schemas
    .object({
      createdAt: core.schemas.property("created_at", core.schemas.date()),
      updatedAt: core.schemas.property("updated_at", core.schemas.date()),
      category: core.schemas.lazy(() => serializers.connect.WorkPlatformCategory),
      status: core.schemas.lazy(() => serializers.connect.Status),
      url: core.schemas.string(),
      products: core.schemas.lazyObject(() => serializers.connect.Products),
    })
    .extend(core.schemas.lazyObject(() => serializers.connect.WorkPlatformAttribute));

export declare namespace WorkPlatform {
  interface Raw extends serializers.connect.WorkPlatformAttribute.Raw {
    created_at: string;
    updated_at: string;
    category: serializers.connect.WorkPlatformCategory.Raw;
    status: serializers.connect.Status.Raw;
    url: string;
    products: serializers.connect.Products.Raw;
  }
}
