/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const WorkPlatformCategory: core.schemas.Schema<
  WorkPlatformCategory.Raw,
  PhylloConnectApi.connect.WorkPlatformCategory
> = core.schemas.string().transform<PhylloConnectApi.connect.WorkPlatformCategory>({
  parse: (value) => PhylloConnectApi.connect.WorkPlatformCategory._parse(value),
  json: ({ value }) => value,
});

export declare namespace WorkPlatformCategory {
  type Raw = string;
}
