/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const AccountId: core.schemas.Schema<AccountId.Raw, PhylloConnectApi.connect.AccountId> = core.schemas.string();

export declare namespace AccountId {
  type Raw = string;
}
