/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AccountData: core.schemas.ObjectSchema<AccountData.Raw, PhylloConnectApi.connect.AccountData> =
  core.schemas.object({
    identity: core.schemas.lazyObject(() => schemas.connect.IdentityData).optional(),
    engagement: core.schemas.lazyObject(() => schemas.connect.EngagementData).optional(),
    income: core.schemas.lazyObject(() => schemas.connect.IncomeData).optional(),
  });

export declare namespace AccountData {
  interface Raw {
    identity?: schemas.connect.IdentityData.Raw | null;
    engagement?: schemas.connect.EngagementData.Raw | null;
    income?: schemas.connect.IncomeData.Raw | null;
  }
}
