/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const AccountStatus: core.schemas.Schema<AccountStatus.Raw, PhylloConnectApi.connect.AccountStatus> =
  core.schemas.string().transform<PhylloConnectApi.connect.AccountStatus>({
    parse: (value) => {
      switch (value) {
        case "CONNECTED": {
          return PhylloConnectApi.connect.AccountStatus.Connected;
        }
        case "NOT_CONNECTED": {
          return PhylloConnectApi.connect.AccountStatus.NotConnected;
        }
        case "SESSION_EXPIRED": {
          return PhylloConnectApi.connect.AccountStatus.SessionExpired;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace AccountStatus {
  type Raw = string;
}
