/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AllAccountsResponse: core.schemas.ObjectSchema<
  AllAccountsResponse.Raw,
  PhylloConnectApi.connect.AllAccountsResponse
> = core.schemas.object({
  data: core.schemas.list(core.schemas.lazyObject(() => schemas.connect.Account)),
  metadata: core.schemas.lazyObject(() => schemas.connect.Metadata),
});

export declare namespace AllAccountsResponse {
  interface Raw {
    data: schemas.connect.Account.Raw[];
    metadata: schemas.connect.Metadata.Raw;
  }
}
