/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const AllUsersResponse: core.schemas.ObjectSchema<
  AllUsersResponse.Raw,
  PhylloConnectApi.connect.AllUsersResponse
> = core.schemas.object({
  data: core.schemas.list(core.schemas.lazyObject(() => schemas.connect.User)),
  metadata: core.schemas.lazyObject(() => schemas.connect.Metadata),
});

export declare namespace AllUsersResponse {
  interface Raw {
    data: schemas.connect.User.Raw[];
    metadata: schemas.connect.Metadata.Raw;
  }
}
