/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const Audience: core.schemas.ObjectSchema<Audience.Raw, PhylloConnectApi.connect.Audience> = core.schemas.object(
  {
    isSupported: core.schemas.property("is_supported", core.schemas.boolean()),
  }
);

export declare namespace Audience {
  interface Raw {
    is_supported: boolean;
  }
}
