/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const EngagementAudienceData: core.schemas.ObjectSchema<
  EngagementAudienceData.Raw,
  PhylloConnectApi.connect.EngagementAudienceData
> = core.schemas.object({
  status: core.schemas.lazy(() => schemas.connect.DataStatus),
  lastSyncAt: core.schemas.property("last_sync_at", core.schemas.date().optional()),
  refreshSince: core.schemas.property("refresh_since", core.schemas.date().optional()),
  dataAvailableFrom: core.schemas.property("data_available_from", core.schemas.date().optional()),
  monitorType: core.schemas.property(
    "monitor_type",
    core.schemas.lazy(() => schemas.connect.MonitoringType)
  ),
});

export declare namespace EngagementAudienceData {
  interface Raw {
    status: schemas.connect.DataStatus.Raw;
    last_sync_at?: string | null;
    refresh_since?: string | null;
    data_available_from?: string | null;
    monitor_type: schemas.connect.MonitoringType.Raw;
  }
}
