/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const ExternalId: core.schemas.Schema<ExternalId.Raw, PhylloConnectApi.connect.ExternalId> =
  core.schemas.string();

export declare namespace ExternalId {
  type Raw = string;
}
