/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const IdentityData: core.schemas.ObjectSchema<IdentityData.Raw, PhylloConnectApi.connect.IdentityData> =
  core.schemas.object({
    status: core.schemas.lazy(() => schemas.connect.DataStatus),
    lastSyncAt: core.schemas.property("last_sync_at", core.schemas.date().optional()),
    monitorType: core.schemas.property(
      "monitor_type",
      core.schemas.lazy(() => schemas.connect.MonitoringType)
    ),
    audience: core.schemas.lazyObject(() => schemas.connect.IdentityAudienceData).optional(),
  });

export declare namespace IdentityData {
  interface Raw {
    status: schemas.connect.DataStatus.Raw;
    last_sync_at?: string | null;
    monitor_type: schemas.connect.MonitoringType.Raw;
    audience?: schemas.connect.IdentityAudienceData.Raw | null;
  }
}
