/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const MonitoringType: core.schemas.Schema<MonitoringType.Raw, PhylloConnectApi.connect.MonitoringType> =
  core.schemas.string().transform<PhylloConnectApi.connect.MonitoringType>({
    parse: (value) => {
      switch (value) {
        case "STANDARD": {
          return PhylloConnectApi.connect.MonitoringType.Standard;
        }
        case "ON_DEMAND": {
          return PhylloConnectApi.connect.MonitoringType.OnDemand;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace MonitoringType {
  type Raw = string;
}
