/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const SDKTokenRequest: core.schemas.ObjectSchema<SDKTokenRequest.Raw, PhylloConnectApi.connect.SDKTokenRequest> =
  core.schemas.object({
    userId: core.schemas.property(
      "user_id",
      core.schemas.lazy(() => schemas.connect.UserId)
    ),
    products: core.schemas.list(core.schemas.lazy(() => schemas.connect.PhylloProducts)),
  });

export declare namespace SDKTokenRequest {
  interface Raw {
    user_id: schemas.connect.UserId.Raw;
    products: schemas.connect.PhylloProducts.Raw[];
  }
}
