/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const Status: core.schemas.Schema<Status.Raw, PhylloConnectApi.connect.Status> = core.schemas
  .string()
  .transform<PhylloConnectApi.connect.Status>({
    parse: (value) => {
      switch (value) {
        case "ACTIVE": {
          return PhylloConnectApi.connect.Status.Active;
        }
        case "INACTIVE": {
          return PhylloConnectApi.connect.Status.Inactive;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace Status {
  type Raw = string;
}
