/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PhylloConnectApi } from "../../..";
import * as core from "../../../core";

export const SwitchProduct: core.schemas.ObjectSchema<SwitchProduct.Raw, PhylloConnectApi.connect.SwitchProduct> =
  core.schemas.object({
    isSupported: core.schemas.property("is_supported", core.schemas.boolean()),
  });

export declare namespace SwitchProduct {
  interface Raw {
    is_supported: boolean;
  }
}
