/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ConnectClient } from "./resources/connect/client/Client";

export declare namespace PhylloConnectApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      credentials?: core.Supplier<core.BasicAuth>;
    };
  }
}

export class PhylloConnectApiClient {
  constructor(private readonly options: PhylloConnectApiClient.Options) {}

  #connect: ConnectClient | undefined;

  public get connect(): ConnectClient {
    return (this.#connect ??= new ConnectClient(this.options));
  }
}
