/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../core";
import { Client as ConnectServiceClient } from "./connect/client/Client";

export namespace Client {
  export interface Options {
    _origin: string;
    _credentials?: core.Supplier<core.BasicAuth>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #connect: ConnectServiceClient | undefined;

  public get connect(): ConnectServiceClient {
    return (this.#connect ??= new ConnectServiceClient({
      _origin: this.options._origin,
      _credentials: this.options._credentials,
    }));
  }
}
